### PR TITLE
Sets up extension using plasmo

### LINKED ISSUE #1: Bootstrap the project with ReactJS and TypeScript

### PR DESCRIPTION
**Pull request by TheoOkafor**
Resolves #1

### CODE REVIEW

**Review by iamstarcode — COMMENTED** [review]
👌

**Review by iamstarcode — DISMISSED** [review]
👌

**Review by Riri202 — COMMENTED** [review]
LGTM 👍🏽

**Comment by iamstarcode** [comment]
I'll need this PR to be first merged before, I can go ahead to add shadcn UI

**Pull request merged**
